"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import {flushSync} from 'react-dom';
import {Building2,LayoutDashboard,Megaphone,CalendarDays,Wrench,ShieldCheck,ArrowUpRight,Plus,Bell,ArrowRight,Search,RefreshCw,ChevronRight,Users,LogOut,LockKeyhole} from 'lucide-react';
import {Sidebar,SidebarProvider,SidebarContent,SidebarHeader,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Input} from '@/components/ui/input';
import {Skeleton} from '@/components/ui/skeleton';
import {Toaster,toast} from 'sonner';
import {profiles,areas,statuses,dateLabel,timeLabel,today,type Entry,type Kind,type Profile} from '@/lib/condo';
import {Choice,Badge,NoResults,CreateForm,Details} from './forms';
type View='dashboard'|Kind|'updates'|'about';
const nav=[{id:'dashboard',title:'Visão geral',icon:LayoutDashboard},{id:'notice',title:'Comunicados',icon:Megaphone},{id:'booking',title:'Reservas',icon:CalendarDays},{id:'maintenance',title:'Manutenção',icon:Wrench},{id:'incident',title:'Ocorrências',icon:ShieldCheck}] as const;
const titles:Record<View,string>={dashboard:'Tudo em ordem, por aqui.',notice:'Informação que aproxima.',booking:'Um espaço para bons momentos.',maintenance:'Cuidar faz parte.',incident:'Sua voz tem espaço.',updates:'Cada passo, acompanhado.',about:'Tecnologia para morar melhor.'};
const subtitles:Record<View,string>={dashboard:'Acompanhe o dia a dia do seu condomínio em um só lugar.',notice:'Os avisos importantes do Residencial Horizonte.',booking:'Confira a agenda e solicite sua próxima reserva.',maintenance:'Registre problemas e acompanhe a solução.',incident:'Um canal reservado entre você e a administração.',updates:'Veja as atualizações dos registros disponíveis para o seu perfil.',about:'Conheça a proposta e as pessoas por trás do CondoConecta.'};
const createLabels:Record<Kind,string>={notice:'Publicar comunicado',booking:'Solicitar reserva',maintenance:'Solicitar manutenção',incident:'Registrar ocorrência'};
const kindLabel:Record<Kind,string>={notice:'Comunicado',booking:'Reserva',maintenance:'Manutenção',incident:'Ocorrência'};
function Navigation({view,onNavigate}:{view:View;onNavigate:(v:View)=>void}){const {setOpenMobile}=useSidebar();return <SidebarMenu>{nav.map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton isActive={view===n.id} onClick={()=>{onNavigate(n.id);setOpenMobile(false)}}><n.icon/><span>{n.title}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu>}
export default function CondoApp(){
 const [view,setView]=useState<View>('dashboard');
 const [profile,setProfile]=useState<Profile>('admin');
 const [entries,setEntries]=useState<Entry[]>([]);
 const [loading,setLoading]=useState(true);
 const [auth,setAuth]=useState(false);
 const [error,setError]=useState('');
 const [query,setQuery]=useState('');
 const [filter,setFilter]=useState('all');
 const [day,setDay]=useState('');
 const [dialog,setDialog]=useState<{kind:Kind;area?:string}|null>(null);
 const [selected,setSelected]=useState<string|null>(null);
 const [busy,setBusy]=useState(false);
 const [refetch,setRefetch]=useState(0);
 const actor=profiles[profile];
 const state=useRef({entries,profile,auth});
 state.current={entries,profile,auth};
 const navigate=useCallback((next:View)=>{setView(next);setQuery('');setFilter('all');setDay('');setSelected(null)},[]);
 useEffect(()=>{
  const c=new AbortController();setLoading(true);setError('');setEntries([]);setSelected(null);
  fetch('/api/condo',{headers:{'x-demo-profile':profile},signal:c.signal}).then(async r=>{
   const data=await r.json() as {entries:Entry[];error?:string};if(r.status===401){setAuth(false);return}if(!r.ok)throw Error(data.error||"Erro ao carregar.");
   setAuth(true);setEntries(data.entries);
  }).catch(e=>{if(e.name!=='AbortError')setError(e.message||'Não foi possível carregar os dados.')}).finally(()=>{if(!c.signal.aborted)setLoading(false)});
  return()=>c.abort();
 },[profile,refetch]);
 useEffect(()=>{
  type Tool={name:string;title:string;description:string;inputSchema:object;annotations:object;execute:(v:unknown)=>unknown};
  const context=(document as Document&{modelContext?:{registerTool:(t:Tool,o:{signal:AbortSignal})=>unknown}}).modelContext;
  if(!context?.registerTool)return;
  const c=new AbortController();
  const tools:Tool[]=[
   {name:'consultar_registros_condominio',title:'Consultar registros',description:'Lista os registros já carregados e autorizados para o perfil de demonstração atual.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Não forneça parâmetros.');if(!state.current.auth)throw Error('Entre no ambiente primeiro.');return {perfil:state.current.profile,registros:state.current.entries.map(e=>({id:e.id,titulo:e.title,tipo:e.kind,situacao:statuses[e.status]}))}}},
   {name:'abrir_formulario_solicitacao',title:'Abrir formulário',description:'Abre o formulário de manutenção ou ocorrência. Não envia nem cria o registro.',inputSchema:{type:'object',properties:{tipo:{type:'string',enum:['maintenance','incident']}},required:['tipo'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const v=input as {tipo?:string};if(!v||!['maintenance','incident'].includes(v.tipo??'')||Object.keys(v).some(k=>k!=='tipo'))throw Error('Tipo inválido.');if(!state.current.auth)throw Error('Entre no ambiente primeiro.');flushSync(()=>setDialog({kind:v.tipo as Kind}));return {formulario:v.tipo,aberto:true,registroCriado:false}}}
  ];
  for(const t of tools)try{Promise.resolve(context.registerTool(t,{signal:c.signal})).catch(()=>{})}catch{}
  return()=>c.abort();
 },[]);
 async function mutate(method:string,payload:object){
  setBusy(true);
  try{const r=await fetch('/api/condo',{method,headers:{'Content-Type':'application/json','x-demo-profile':profile},body:JSON.stringify(payload)});const data=await r.json() as {entry:Entry;error?:string};if(!r.ok)throw Error(data.error||'Não foi possível salvar.');setEntries(old=>[data.entry,...old.filter(e=>e.id!==data.entry.id)]);toast.success(method==='POST'?'Registro salvo com sucesso.':'Atualização salva.');return data.entry as Entry;}finally{setBusy(false)}
 }
 function open(kind:Kind,area?:string){if(auth)setDialog({kind,area})}
 const current=entries.find(e=>e.id===selected);
 const filtered=entries.filter(e=>e.kind===view).filter(e=>filter==='all'||e.status===filter).filter(e=>!day||e.day===day).filter(e=>(e.title+' '+e.description+' '+e.location+' '+e.area).toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR')));
 const notices=entries.filter(e=>e.kind==='notice'&&e.status==='published');
 const bookings=entries.filter(e=>e.kind==='booking'&&['pending','confirmed'].includes(e.status)&&e.day>=today()).sort((a,b)=>(a.day+timeLabel(a.start)).localeCompare(b.day+timeLabel(b.start)));
 const maintenance=entries.filter(e=>e.kind==='maintenance'&&!['completed','cancelled'].includes(e.status));
 const incidents=entries.filter(e=>e.kind==='incident'&&e.status!=='closed');
 const date=new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'numeric',month:'long',timeZone:'America/Sao_Paulo'}).format(new Date());
 const primaryKind:Kind=view==='notice'?'notice':view==='booking'?'booking':view==='incident'?'incident':'maintenance';
 const canCreate=auth&&(primaryKind!=='notice'||actor.manager)&&(primaryKind!=='booking'||profile!=='employee');
 const updates=entries.flatMap(e=>e.history.map((h,i)=>({e,h,key:e.id+i}))).sort((a,b)=>b.h.at.localeCompare(a.h.at)).slice(0,40);
 function row(e:Entry){return <button key={e.id} className="record-row" onClick={()=>setSelected(e.id)} disabled={e.masked}><span className={'record-icon '+(e.kind==='booking'?'blue':'teal')}>{e.kind==='booking'?<CalendarDays size={19}/>:e.kind==='incident'?<ShieldCheck size={19}/>:<Wrench size={19}/>}</span><span className="record-body"><b>{e.title}</b><span>{e.kind==='booking'?e.area+' · '+dateLabel(e.day)+' · '+timeLabel(e.start)+'–'+timeLabel(e.end):e.location+' · '+dateLabel(e.created)}</span>{e.kind==='maintenance'&&<small>{e.assigned?'Responsável: '+profiles.employee.name:'Aguardando atribuição'}{e.priority==='Alta'?' · Prioridade alta':''}</small>}</span><Badge status={e.status}/>{!e.masked&&<ChevronRight size={17}/>}</button>}
 function notice(e:Entry,i:number){return <article className={'notice '+(i===0?'featured':'')} key={e.id}><span className={'pill '+(i===0?'teal':'blue')}>{e.category.toUpperCase()}</span>{e.status==='archived'&&<Badge status={e.status}/>}<button className="notice-title" onClick={()=>setSelected(e.id)}><h3>{e.title}</h3></button><p>{e.description}</p><small>{profiles[e.author]?.role} · {dateLabel(e.created)}</small></article>}
 return <SidebarProvider><Toaster richColors position="top-right"/><a className="skip-link" href="#conteudo">Pular para o conteúdo</a><Sidebar className="app-sidebar"><SidebarHeader><div className="brand"><div className="brand-icon"><Building2 size={24}/></div><span>condo<span className="brand-light">conecta</span><small>GESTÃO CONDOMINIAL</small></span></div></SidebarHeader><SidebarContent><div className="condominium"><span className="building-small"><Building2 size={20}/></span><div><b>Residencial Horizonte</b><small>Seu condomínio conectado</small></div></div><p className="nav-label">PRINCIPAL</p><Navigation view={view} onNavigate={navigate}/><div className="sidebar-note"><ShieldCheck size={20}/><p>Mais organização.<br/>Mais tranquilidade.</p><small>Um lugar para cuidar do que é de todos.</small></div><button className="about-link" onClick={()=>navigate('about')}><Users size={17}/>Sobre o projeto</button></SidebarContent><SidebarFooter><div className="sidebar-person"><span className="avatar">{actor.initials}</span><div><b>{actor.name}</b><small>{actor.role} · {actor.unit}</small></div></div></SidebarFooter></Sidebar><div className="app-main"><header className="topbar"><div className="topbar-left"><SidebarTrigger/><span>Residencial Horizonte</span></div><div className="topbar-right"><span className="demo-tag">DEMONSTRAÇÃO</span><button className="icon-button" aria-label="Ver atualizações" onClick={()=>navigate('updates')}><Bell size={19}/></button><span className="avatar avatar-light">{actor.initials}</span></div></header><main id="conteudo" className="workspace">
 <div className="page-heading"><div><p className="eyebrow">{date.toUpperCase()}</p><h1>{titles[view]}</h1><p>{subtitles[view]}</p></div>{canCreate&&!['about','updates'].includes(view)&&<button className="primary" onClick={()=>open(primaryKind)}><Plus size={18}/>{view==='dashboard'?'Nova solicitação':createLabels[primaryKind]}</button>}</div>
 {auth&&<div className="demo-controls"><div><b>Ambiente acadêmico</b><span>Dados fictícios. Experimente os diferentes perfis.</span></div><div className="demo-actions"><Choice label="Testar perfil" value={profile} onChange={v=>{setProfile(v as Profile);setDialog(null)}} disabled={busy} options={Object.entries(profiles).map(([value,p])=>({value,label:p.role+' · '+p.name}))}/><button className="icon-button" title="Atualizar dados" aria-label="Atualizar dados" disabled={loading||busy} onClick={()=>setRefetch(x=>x+1)}><RefreshCw size={17}/></button><a className="icon-button" href="/signout-with-chatgpt?return_to=/" aria-label="Sair da conta"><LogOut size={17}/></a></div></div>}
 {error?<div role="alert" className="error-box"><p>{error}</p><button className="text-link" onClick={()=>setRefetch(x=>x+1)}>Tentar novamente</button></div>:loading?<div aria-label="Carregando dados" className="loading-grid"><Skeleton className="h-36"/><Skeleton className="h-36"/><Skeleton className="h-64 col-span-2"/></div>:!auth?<section className="login-panel"><div className="login-mark"><Building2 size={34}/></div><span className="eyebrow">BEM-VINDO AO CONDOCONECTA</span><h2>Seu condomínio,<br/>em um só lugar.</h2><p>Comunicados, reservas e solicitações com acompanhamento do início ao fim.</p><a className="primary" href="/signin-with-chatgpt?return_to=/" target="_top">Entrar na demonstração <ArrowRight size={18}/></a><small>Use sua conta ChatGPT. O ambiente contém exemplos fictícios e permite testar cinco perfis.</small></section>:<>
 {view==='dashboard'&&<><div className="metrics">{[{label:'Chamados em aberto',value:maintenance.length,note:'Acompanhe as solicitações',icon:Wrench,to:'maintenance'},{label:'Reservas ativas',value:bookings.length,note:'Espaços para compartilhar',icon:CalendarDays,to:'booking'},{label:'Comunicados',value:notices.length,note:'Informação que aproxima',icon:Megaphone,to:'notice'},{label:'Ocorrências abertas',value:incidents.length,note:'Atendimento com privacidade',icon:ShieldCheck,to:'incident'}].map(m=><button className="metric" key={m.label} onClick={()=>navigate(m.to as View)}><div className="metric-top"><span>{m.label}</span><m.icon size={20}/></div><strong>{m.value}</strong><small>{m.note}</small></button>)}</div><div className="dashboard-grid"><section className="panel"><div className="section-heading"><h2>Últimos comunicados</h2><button className="text-link" onClick={()=>navigate('notice')}>Ver todos <ArrowUpRight size={16}/></button></div>{notices.length?notices.slice(0,2).map(notice):<NoResults text="Os novos comunicados aparecerão aqui."/>}</section><div><section className="quick-panel"><span className="eyebrow">COMO PODEMOS AJUDAR?</span><h2>Seu próximo passo,<br/>sem complicação.</h2>{[{label:'Reservar um espaço',icon:CalendarDays,kind:'booking'},{label:'Solicitar manutenção',icon:Wrench,kind:'maintenance'},{label:'Registrar ocorrência',icon:ShieldCheck,kind:'incident'}].filter(a=>a.kind!=='booking'||profile!=='employee').map(a=><button key={a.label} onClick={()=>open(a.kind as Kind)}><a.icon size={19}/><span>{a.label}</span><ArrowRight size={17}/></button>)}</section><div className="info-note"><ShieldCheck size={22}/><div><b>Sua privacidade importa</b><p>Ocorrências são acessíveis apenas ao autor e à gestão.</p></div></div></div></div><section className="panel section-space"><div className="section-heading"><h2>{actor.manager?'Solicitações em acompanhamento':'Seu acompanhamento'}</h2><button className="text-link" onClick={()=>navigate('maintenance')}>Ver chamados <ArrowUpRight size={16}/></button></div>{maintenance.length?maintenance.slice(0,4).map(row):<NoResults text="Nenhum chamado em aberto para este perfil."/>}</section><section className="panel section-space"><div className="section-heading"><h2>Próximas reservas</h2><button className="text-link" onClick={()=>navigate('booking')}>Consultar agenda <ArrowUpRight size={16}/></button></div>{bookings.length?bookings.slice(0,3).map(row):<NoResults text="A agenda está livre. Que tal reservar um espaço?"/>}</section></>}
 {['notice','booking','maintenance','incident'].includes(view)&&<>
 {view==='booking'&&<div className="area-grid">{areas.map((area,i)=><article className="area-card" key={area}><span className="area-number">0{i+1}</span><CalendarDays size={24}/><h2>{area}</h2><p>Das 8h às 22h · até 6 horas</p><button className="text-link" disabled={profile==='employee'} onClick={()=>open('booking',area)}>Solicitar reserva <ArrowUpRight size={16}/></button></article>)}</div>}
 {view==='incident'&&<div className="privacy-banner"><LockKeyhole size={18}/><span>{actor.manager?'Acesso da gestão. Trate os relatos com discrição e compartilhe apenas o necessário.':'Seus relatos são visíveis apenas para você e para a gestão.'}</span></div>}
 <section className="panel"><div className="list-toolbar"><div className="search-field"><Search size={17}/><Input aria-label="Buscar registros" placeholder="Buscar por título, local ou descrição…" value={query} onChange={e=>setQuery(e.target.value)}/></div><Choice label="Filtrar por situação" value={filter} onChange={setFilter} options={[{value:'all',label:'Todas as situações'},...Array.from(new Set(entries.filter(e=>e.kind===view).map(e=>e.status))).map(s=>({value:s,label:statuses[s]}))]}/>{view==='booking'&&<Input type="date" aria-label="Filtrar reservas por data" value={day} onChange={e=>setDay(e.target.value)} className="date-filter"/>}{(query||filter!=='all'||day)&&<button className="text-link" onClick={()=>{setQuery('');setFilter('all');setDay('')}}>Limpar</button>}</div><div className="list-caption">{filtered.length} {filtered.length===1?'registro encontrado':'registros encontrados'}{view==='booking'?' · horários de Brasília':''}</div>{filtered.length?(view==='notice'?filtered.map(notice):filtered.map(row)):<NoResults/>}</section></>}
 {view==='updates'&&<section className="panel"><div className="section-heading"><h2>Histórico recente</h2><span className="muted">{updates.length} atualizações</span></div>{updates.length?updates.map(({e,h,key})=><button className="update-row" key={key} onClick={()=>setSelected(e.id)}><span className="timeline-dot"/><div><b>{e.title}</b><p>{h.text}</p><small>{h.actor} · {dateLabel(h.at)}{h.internal?' · Nota interna':''}</small></div><ChevronRight size={17}/></button>):<NoResults text="As atualizações dos seus registros aparecerão aqui."/>}</section>}
 {view==='about'&&<section className="panel about-panel"><span className="pill teal">NEXOHAB TECNOLOGIA</span><h2>CondoConecta</h2><p>Uma aplicação web para centralizar comunicados, reservas de áreas comuns, manutenção e ocorrências. Criada para a atividade de proposta de uma empresa de tecnologia.</p><h3>Nossa equipe</h3>{[['Luis Gustavo','Full Stack, Back-end e Product Owner'],['João Vittor Monteiro','Front-end · comunicados e manutenção'],['João Vitor Simões','Front-end · reservas, ocorrências e painel'],['João Gabriel Camara','Back-end · comunicados e manutenção'],['João Carlos','Back-end · reservas e ocorrências']].map(([name,role])=><div className="team-row" key={name}><span className="avatar avatar-light">{name.split(' ').slice(0,2).map(n=>n[0]).join('')}</span><div><b>{name}</b><p>{role}</p></div></div>)}<h3>Como experimentar</h3><p>Use o seletor de perfis para simular morador, funcionário, síndico e administradora. Os registros ficam salvos no seu ambiente. Cada conta tem sua própria demonstração, sem compartilhar dados com outros visitantes.</p><div className="privacy-banner"><ShieldCheck size={20}/><span>Versão acadêmica. A troca de perfil serve à apresentação e não representa um cadastro real de moradores. Não insira informações pessoais reais.</span></div><h3>Regras da versão</h3><p>Reservas: de amanhã até 90 dias, entre 8h e 22h, por até 6 horas. Pedidos pendentes bloqueiam o horário até aprovação, recusa ou cancelamento. Chamados não são um canal de emergência.</p></section>}
 </>}
 <footer className="page-footer"><span>CondoConecta · NexoHab Tecnologia</span><span>Projeto acadêmico • exemplos fictícios</span></footer></main></div>
 <Dialog open={!!dialog} onOpenChange={v=>{if(!v&&!busy)setDialog(null)}}><DialogContent className="form-dialog" onInteractOutside={e=>{if(busy)e.preventDefault()}}><DialogHeader><DialogTitle>{dialog?createLabels[dialog.kind]:''}</DialogTitle><DialogDescription>{dialog?.kind==='booking'?'Escolha um horário e aguarde a aprovação da gestão.':dialog?.kind==='incident'?'Seu relato será enviado de forma reservada à gestão.':'Preencha as informações para manter todos os detalhes organizados.'}</DialogDescription></DialogHeader>{dialog&&<CreateForm key={dialog.kind+dialog.area} kind={dialog.kind} area={dialog.area} entries={entries} busy={busy} onCancel={()=>setDialog(null)} onSubmit={async value=>{const entry=await mutate('POST',value);setDialog(null);navigate(entry.kind);setSelected(entry.id)}}/>}</DialogContent></Dialog>
 <Sheet open={!!current} onOpenChange={v=>{if(!v&&!busy)setSelected(null)}}><SheetContent className="detail-sheet"><SheetHeader><SheetTitle>{current?.title}</SheetTitle><SheetDescription>{current?kindLabel[current.kind]+' · Protocolo '+(current.id.includes('::')?'DEMO-'+current.id.split('-').pop():current.id.slice(0,8).toUpperCase()):''}</SheetDescription></SheetHeader>{current&&<Details key={current.id} entry={current} profile={profile} busy={busy} onSubmit={value=>mutate('PATCH',value)}/>}</SheetContent></Sheet>
 </SidebarProvider>
}

