"use client";
import {useEffect,useState,type FormEvent} from 'react';
import {CalendarDays,Building2,Wrench,Clock,MapPin,Users,LockKeyhole,CheckCircle2} from 'lucide-react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Checkbox} from '@/components/ui/checkbox';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import {profiles,areas,statuses,allowedTransitions,dateLabel,timeLabel,tomorrow,type Entry,type Kind,type Profile} from '@/lib/condo';
type CreateInput={kind:Kind;title:string;description:string;category:string;location:string;priority:string;area:string;day:string;start:number;end:number};
const categories:Record<Kind,string[]>={notice:['Convivência','Manutenção programada','Áreas comuns','Administração'],booking:['Reserva'],maintenance:['Elétrica','Hidráulica','Limpeza','Estrutura','Outros'],incident:['Convivência','Segurança','Uso das áreas','Outros']};
export function Choice({label,value,onChange,options,disabled=false}:{label:string;value:string;onChange:(v:string)=>void;options:{value:string;label:string}[];disabled?:boolean}){
 return <Select value={value} onValueChange={onChange} disabled={disabled}><SelectTrigger aria-label={label} className="choice"><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>;
}
export function Badge({status}:{status:string}){const color=['confirmed','completed','published','closed'].includes(status)?'teal':['pending','open','registered','waiting'].includes(status)?'amber':['cancelled','rejected'].includes(status)?'red':'blue';return <span className={'pill '+color}>{statuses[status]??status}</span>}
export function NoResults({text='Experimente outro filtro ou crie um novo registro.'}:{text?:string}){return <Empty><EmptyHeader><EmptyTitle>Nenhum registro por aqui</EmptyTitle><EmptyDescription>{text}</EmptyDescription></EmptyHeader></Empty>}
export function CreateForm({kind,area,entries,busy,onSubmit,onCancel}:{kind:Kind;area?:string;entries:Entry[];busy:boolean;onSubmit:(value:CreateInput)=>Promise<void>;onCancel:()=>void}){
 const [category,setCategory]=useState(categories[kind][0]);const [priority,setPriority]=useState('Normal');const [selectedArea,setArea]=useState<string>(area??areas[0]);const [day,setDay]=useState('');const [start,setStart]=useState('10');const [end,setEnd]=useState('12');const [error,setError]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');const f=new FormData(e.currentTarget);try{await onSubmit({kind,title:kind==='booking'?'Reserva · '+selectedArea:String(f.get('title')??''),description:String(f.get('description')??''),location:String(f.get('location')??''),category,priority,area:kind==='booking'?selectedArea:'',day:kind==='booking'?day:'',start:kind==='booking'?Number(start):0,end:kind==='booking'?Number(end):0})}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.');}}
 const occupied=entries.filter(e=>e.kind==='booking'&&e.area===selectedArea&&e.day===day&&['pending','confirmed'].includes(e.status)).sort((a,b)=>a.start-b.start);
 return <form onSubmit={submit} className="entry-form"><fieldset disabled={busy}>
 {kind==='booking'?<><label>Área comum<Choice label="Área comum" value={selectedArea} onChange={setArea} options={areas.map(a=>({value:a,label:a}))}/></label><label>Data<Input required type="date" min={tomorrow()} value={day} onChange={e=>setDay(e.target.value)} aria-label="Data da reserva"/></label><div className="two-fields"><label>Início<Choice label="Horário de início" value={start} onChange={setStart} options={Array.from({length:14},(_,i)=>({value:String(i+8),label:timeLabel(i+8)}))}/></label><label>Fim<Choice label="Horário de fim" value={end} onChange={setEnd} options={Array.from({length:14},(_,i)=>({value:String(i+9),label:timeLabel(i+9)}))}/></label></div><div className="availability"><Clock size={17}/><span>{day?occupied.length?'Horários ocupados: '+occupied.map(e=>timeLabel(e.start)+'–'+timeLabel(e.end)).join(', '):'Nenhuma reserva neste dia.':'Selecione uma data para consultar a agenda.'}</span></div><p className="form-hint">Horário de Brasília. Reserve com pelo menos um dia de antecedência, por até 6 horas.</p></>:<><label>Título<Input required name="title" minLength={4} maxLength={120} placeholder={kind==='notice'?'Qual é o assunto do comunicado?':'Resuma o que aconteceu'}/></label><label>Categoria<Choice label="Categoria" value={category} onChange={setCategory} options={categories[kind].map(c=>({value:c,label:c}))}/></label>{kind!=='notice'&&<label>Local<Input required name="location" maxLength={120} placeholder="Ex.: Bloco A, corredor do 2º andar"/></label>}{kind==='maintenance'&&<label>Prioridade<Choice label="Prioridade" value={priority} onChange={setPriority} options={['Baixa','Normal','Alta'].map(p=>({value:p,label:p}))}/></label>}</>}
 <label>{kind==='booking'?'Finalidade da reserva':'Descrição'}<Textarea name="description" required minLength={8} maxLength={3000} rows={4} placeholder={kind==='booking'?'Ex.: confraternização da família':'Conte os detalhes necessários ao atendimento.'}/></label>
 {kind==='incident'&&<p className="form-hint"><LockKeyhole size={14}/> Evite informações pessoais desnecessárias. Use apenas dados fictícios.</p>}
 {error&&<p className="form-error" role="alert">{error}</p>}
 <div className="form-actions"><button type="button" className="secondary" onClick={onCancel}>Voltar</button><button className="primary" type="submit" disabled={busy}>{busy?'Salvando…':kind==='notice'?'Publicar comunicado':kind==='booking'?'Enviar solicitação':'Registrar solicitação'}</button></div>
 </fieldset></form>
}
export function Details({entry:e,profile,busy,onSubmit}:{entry:Entry;profile:Profile;busy:boolean;onSubmit:(v:object)=>Promise<unknown>}){
 const [status,setStatus]=useState(e.status);const [assigned,setAssigned]=useState(e.assigned||'none');const [internal,setInternal]=useState(false);const [note,setNote]=useState('');const [error,setError]=useState('');
 useEffect(()=>{setStatus(e.status);setAssigned(e.assigned||'none')},[e.status,e.assigned]);
 const choices=allowedTransitions(e,profile);const manager=profiles[profile].manager;const canNote=manager||e.author===profile&&e.kind!=='notice'||profile==='employee'&&e.assigned==='employee'&&e.kind==='maintenance';
 async function submit(ev:FormEvent){ev.preventDefault();setError('');try{await onSubmit({id:e.id,version:e.version,status,note,internal,...(manager&&e.kind==='maintenance'?{assigned:assigned==='none'?'':assigned}:{})});setNote('');setInternal(false)}catch(err){setError(err instanceof Error?err.message:'Erro ao atualizar.')}}
 return <div className="detail-body"><div className="detail-badges"><Badge status={e.status}/><span className="pill gray">{e.category}</span>{e.priority==='Alta'&&<span className="pill red">Prioridade alta</span>}</div><p className="detail-description">{e.description}</p><div className="detail-meta">{e.location&&<p><MapPin size={16}/>{e.location}</p>}{e.kind==='booking'&&<><p><Building2 size={16}/>{e.area}</p><p><CalendarDays size={16}/>{dateLabel(e.day)} · {timeLabel(e.start)}–{timeLabel(e.end)}</p></>}<p><Users size={16}/>{profiles[e.author]?.name} · {profiles[e.author]?.unit}</p>{e.kind==='maintenance'&&<p><Wrench size={16}/>{e.assigned?profiles.employee.name:'Ainda sem responsável'}</p>}</div>
 <h3>Histórico de acompanhamento</h3><div className="timeline">{e.history.map((h,i)=><div className="timeline-item" key={i}><span className="timeline-dot"/><div><b>{h.actor}</b>{h.internal&&<span className="pill gray">Nota interna</span>}<p>{h.text}</p><small>{dateLabel(h.at)} · {new Intl.DateTimeFormat('pt-BR',{hour:'2-digit',minute:'2-digit',timeZone:'America/Sao_Paulo'}).format(new Date(h.at))}</small></div></div>)}</div>
 {canNote&&<form onSubmit={submit} className="entry-form update-form"><h3>Adicionar atualização</h3><fieldset disabled={busy}>{choices.length>0&&<label>Situação<Choice label="Nova situação" value={status} onChange={setStatus} options={[e.status,...choices].map(s=>({value:s,label:statuses[s]}))}/></label>}{manager&&e.kind==='maintenance'&&<label>Responsável<Choice label="Responsável pelo chamado" value={assigned} onChange={setAssigned} options={[{value:'none',label:'Não atribuído'},{value:'employee',label:profiles.employee.name}]}/></label>}<label>{e.kind==='incident'?'Resposta ou observação':'Mensagem de acompanhamento'}<Textarea aria-label="Mensagem de acompanhamento" required minLength={4} maxLength={1500} value={note} onChange={ev=>setNote(ev.target.value)} placeholder="Descreva a atualização ou justifique a mudança." rows={3}/></label>{manager&&e.kind==='incident'&&<label className="checkbox-label"><Checkbox checked={internal} onCheckedChange={v=>setInternal(v===true)}/>Nota interna (somente a gestão)</label>}{error&&<p className="form-error" role="alert">{error}</p>}<button type="submit" className="primary" disabled={busy}>{busy?'Salvando…':'Salvar atualização'}<CheckCircle2 size={16}/></button></fieldset></form>}
 </div>
}
